appname = MID
httpport = 8085
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
sqlconn = 


host_api = http://localhost:8087/v1/
host_api1 = http://localhost:8087/v1/
host_api2 = http://localhost:8081/v1/
host_api3= http://localhost:8087/v1/